plugins { id 'java' }

group = 'com.maris7.team'
version = '1.0'

java { toolchain { languageVersion = JavaLanguageVersion.of(25) } }

compileJava { options.encoding = 'UTF-8' }
processResources { filteringCharset = 'UTF-8'; filesMatching('plugin.yml') { expand(version: project.version) } }

dependencies {
    compileOnly 'io.papermc.paper:paper-api:26.1.2.build.+'
    compileOnly 'me.clip:placeholderapi:2.11.6'
    compileOnly 'com.github.MilkBowl:VaultAPI:1.7.1'
    compileOnly 'com.zaxxer:HikariCP:7.0.2'
    compileOnly 'org.xerial:sqlite-jdbc:3.53.0.0'
    compileOnly 'com.mysql:mysql-connector-j:9.7.0'
}

jar { archiveBaseName.set('MarisTeam'); archiveVersion.set(''); archiveClassifier.set('') }

