package com.maris7.team.db;

import com.zaxxer.hikari.*;import com.maris7.team.MarisTeam;import java.io.File;import java.sql.*;

public final class Database { private final MarisTeam p; private HikariDataSource ds; public Database(MarisTeam p){this.p=p;}
 public void init(){ try{ HikariConfig c=new HikariConfig(); String type=p.getConfig().getString("database.type","sqlite"); if(type.equalsIgnoreCase("mysql")){c.setJdbcUrl("jdbc:mysql://"+p.getConfig().getString("database.mysql.host")+":"+p.getConfig().getInt("database.mysql.port")+"/"+p.getConfig().getString("database.mysql.database")+"?useSSL=false&autoReconnect=true"); c.setUsername(p.getConfig().getString("database.mysql.username")); c.setPassword(p.getConfig().getString("database.mysql.password")); c.setMaximumPoolSize(p.getConfig().getInt("database.mysql.pool-size",8));} else {File f=new File(p.getDataFolder(),"data.db"); c.setJdbcUrl("jdbc:sqlite:"+f.getAbsolutePath()); c.setMaximumPoolSize(1);} c.setPoolName("MarisTeamPool"); ds=new HikariDataSource(c); migrate(); }catch(Exception e){throw new RuntimeException(e);} }
 public Connection con() throws SQLException{if(ds==null||ds.isClosed())throw new SQLException("MarisTeam database is closed");return ds.getConnection();}
 public boolean isClosed(){return ds==null||ds.isClosed();}
 private void migrate() throws SQLException{ boolean mysql=p.getConfig().getString("database.type","sqlite").equalsIgnoreCase("mysql"); try(Connection c=con(); Statement s=c.createStatement()){if(mysql){s.executeUpdate("CREATE TABLE IF NOT EXISTS teams(id INTEGER PRIMARY KEY AUTO_INCREMENT, name VARCHAR(16) UNIQUE, leader VARCHAR(36), pvp BOOLEAN DEFAULT FALSE, world TEXT, x DOUBLE, y DOUBLE, z DOUBLE, yaw FLOAT, pitch FLOAT)"); s.executeUpdate("CREATE TABLE IF NOT EXISTS members(uuid VARCHAR(36) PRIMARY KEY, name VARCHAR(16), team_id INTEGER, joined_at BIGINT, edit_home BOOLEAN DEFAULT FALSE, manage_members BOOLEAN DEFAULT FALSE, pvp BOOLEAN DEFAULT FALSE, visit_home BOOLEAN DEFAULT FALSE, team_chat BOOLEAN DEFAULT TRUE, chat_toggle BOOLEAN DEFAULT FALSE)"); s.executeUpdate("CREATE TABLE IF NOT EXISTS pending_messages(uuid VARCHAR(36), message TEXT)");}else{s.executeUpdate("CREATE TABLE IF NOT EXISTS teams(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT UNIQUE, leader TEXT, pvp INTEGER DEFAULT 0, world TEXT, x REAL, y REAL, z REAL, yaw REAL, pitch REAL)"); s.executeUpdate("CREATE TABLE IF NOT EXISTS members(uuid TEXT PRIMARY KEY, name TEXT, team_id INTEGER, joined_at INTEGER, edit_home INTEGER DEFAULT 0, manage_members INTEGER DEFAULT 0, pvp INTEGER DEFAULT 0, visit_home INTEGER DEFAULT 0, team_chat INTEGER DEFAULT 1, chat_toggle INTEGER DEFAULT 0)"); s.executeUpdate("CREATE TABLE IF NOT EXISTS pending_messages(uuid TEXT, message TEXT)");}}}
 public java.util.List<String> takePending(java.util.UUID u){ java.util.List<String> out=new java.util.ArrayList<>(); try(Connection c=con(); PreparedStatement ps=c.prepareStatement("SELECT message FROM pending_messages WHERE uuid=?")){ps.setString(1,u.toString()); ResultSet r=ps.executeQuery(); while(r.next())out.add(r.getString(1));}catch(Exception ignored){} try(Connection c=con(); PreparedStatement ps=c.prepareStatement("DELETE FROM pending_messages WHERE uuid=?")){ps.setString(1,u.toString()); ps.executeUpdate();}catch(Exception ignored){} return out;}
 public void close(){ if(ds!=null)ds.close(); }
}
